// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authsnapshot.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAuthSnapshot = `-- name: GetAuthSnapshot :one
SELECT
    u.id AS user_id,
    u.email as email,
    u.name as name,
    o.id AS organization_id,
    o.name AS organization_name,
    o.domain AS organization_domain,
    ua.role AS role,
    CASE
        WHEN ua.disabled_at IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS disabled
FROM users u
JOIN user_organization_assignments ua
  ON ua.user_id = u.id
JOIN organizations o
  ON o.id = ua.organization_id
WHERE u.id = $1 AND o.id = $2
LIMIT 1
`

type GetAuthSnapshotParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

type GetAuthSnapshotRow struct {
	UserID             uuid.UUID `db:"user_id" json:"user_id"`
	Email              string    `db:"email" json:"email"`
	Name               string    `db:"name" json:"name"`
	OrganizationID     uuid.UUID `db:"organization_id" json:"organization_id"`
	OrganizationName   string    `db:"organization_name" json:"organization_name"`
	OrganizationDomain string    `db:"organization_domain" json:"organization_domain"`
	Role               int16     `db:"role" json:"role"`
	Disabled           bool      `db:"disabled" json:"disabled"`
}

func (q *Queries) GetAuthSnapshot(ctx context.Context, arg GetAuthSnapshotParams) (GetAuthSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getAuthSnapshot, arg.UserID, arg.OrganizationID)
	var i GetAuthSnapshotRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.OrganizationDomain,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}
