// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Organization struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Domain    string    `db:"domain" json:"domain"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Session struct {
	Token  string    `db:"token" json:"token"`
	Data   []byte    `db:"data" json:"data"`
	Expiry time.Time `db:"expiry" json:"expiry"`
}

type Task struct {
	ID             string     `db:"id" json:"id"`
	Title          string     `db:"title" json:"title"`
	Description    string     `db:"description" json:"description"`
	Notes          string     `db:"notes" json:"notes"`
	DueBy          *time.Time `db:"due_by" json:"due_by"`
	Priority       int16      `db:"priority" json:"priority"`
	Progress       int16      `db:"progress" json:"progress"`
	Status         int16      `db:"status" json:"status"`
	AssigneeUserID uuid.UUID  `db:"assignee_user_id" json:"assignee_user_id"`
	AssignerUserID uuid.UUID  `db:"assigner_user_id" json:"assigner_user_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time  `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Email     string    `db:"email" json:"email"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type UserOrganizationAssignment struct {
	UserID         uuid.UUID  `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	Role           int16      `db:"role" json:"role"`
	DisabledAt     *time.Time `db:"disabled_at" json:"disabled_at"`
	DisabledReason *string    `db:"disabled_reason" json:"disabled_reason"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
}
