// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserToOrganization = `-- name: AssignUserToOrganization :exec
INSERT INTO user_organization_assignments
    (user_id, organization_id, role)
VALUES
    ($1, $2, $3)
ON CONFLICT (user_id, organization_id) DO NOTHING
`

type AssignUserToOrganizationParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Role           int16     `db:"role" json:"role"`
}

func (q *Queries) AssignUserToOrganization(ctx context.Context, arg AssignUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, assignUserToOrganization, arg.UserID, arg.OrganizationID, arg.Role)
	return err
}

const assignUserToOrganizationTryOwner = `-- name: AssignUserToOrganizationTryOwner :exec
INSERT INTO user_organization_assignments
    (user_id, organization_id, role)
VALUES
    ($1, $2, 3)
ON CONFLICT DO NOTHING
`

type AssignUserToOrganizationTryOwnerParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) AssignUserToOrganizationTryOwner(ctx context.Context, arg AssignUserToOrganizationTryOwnerParams) error {
	_, err := q.db.Exec(ctx, assignUserToOrganizationTryOwner, arg.UserID, arg.OrganizationID)
	return err
}

const getOrgUserRole = `-- name: GetOrgUserRole :one
SELECT
    role, 
    CASE
        WHEN ua.disabled_at IS NOT NULL THEN TRUE
        ELSE FALSE
    END AS disabled
FROM
    user_organization_assignments ua
WHERE
    user_id = $1 AND organization_id = $2
LIMIT 1
`

type GetOrgUserRoleParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

type GetOrgUserRoleRow struct {
	Role     int16 `db:"role" json:"role"`
	Disabled bool  `db:"disabled" json:"disabled"`
}

func (q *Queries) GetOrgUserRole(ctx context.Context, arg GetOrgUserRoleParams) (GetOrgUserRoleRow, error) {
	row := q.db.QueryRow(ctx, getOrgUserRole, arg.UserID, arg.OrganizationID)
	var i GetOrgUserRoleRow
	err := row.Scan(&i.Role, &i.Disabled)
	return i, err
}

const getOrganizationByDomain = `-- name: GetOrganizationByDomain :one
SELECT id, name, domain, created_at FROM organizations WHERE domain = $1
`

func (q *Queries) GetOrganizationByDomain(ctx context.Context, domain string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByDomain, domain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, domain, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByUserID = `-- name: GetOrganizationByUserID :one
SELECT
    o.id, o.name, o.domain, o.created_at
FROM
    organizations o
JOIN
    user_organization_assignments ua
ON
    ua.organization_id = o.id
WHERE
    ua.user_id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationByUserID(ctx context.Context, userID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByUserID, userID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrganizationAssignment = `-- name: GetUserOrganizationAssignment :one
SELECT user_id, organization_id, role, disabled_at, disabled_reason, created_at FROM user_organization_assignments
WHERE user_id = $1 AND organization_id = $2 LIMIT 1
`

type GetUserOrganizationAssignmentParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetUserOrganizationAssignment(ctx context.Context, arg GetUserOrganizationAssignmentParams) (UserOrganizationAssignment, error) {
	row := q.db.QueryRow(ctx, getUserOrganizationAssignment, arg.UserID, arg.OrganizationID)
	var i UserOrganizationAssignment
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($1, name)
WHERE
    id = $2
RETURNING id, name, domain, created_at
`

type UpdateOrganizationParams struct {
	Name           pgtype.Text `db:"name" json:"name"`
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Name, arg.OrganizationID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOrganization = `-- name: UpsertOrganization :one
INSERT INTO organizations 
    (name, domain)
VALUES 
    ($1, $2)
ON CONFLICT (domain) DO UPDATE
    SET domain = organizations.domain -- no-op to return existing row
RETURNING id, name, domain, created_at
`

type UpsertOrganizationParams struct {
	Name   string `db:"name" json:"name"`
	Domain string `db:"domain" json:"domain"`
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, upsertOrganization, arg.Name, arg.Domain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}
