// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    title,
    description,
    priority,
    due_by,
    assignee_user_id,
    assigner_user_id,
    organization_id
) VALUES (
    $1,
    $2,
    $3,
    $4::SMALLINT,
    $5,
    COALESCE($6::UUID, $7),
    $7,
    $8
) RETURNING id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at
`

type CreateTaskParams struct {
	ID             string     `db:"id" json:"id"`
	Title          string     `db:"title" json:"title"`
	Description    string     `db:"description" json:"description"`
	Priority       int16      `db:"priority" json:"priority"`
	DueBy          *time.Time `db:"due_by" json:"due_by"`
	AssigneeUserID *uuid.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	AssignerUserID uuid.UUID  `db:"assigner_user_id" json:"assigner_user_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueBy,
		arg.AssigneeUserID,
		arg.AssignerUserID,
		arg.OrganizationID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.DueBy,
		&i.Priority,
		&i.Progress,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssignerUserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 and organization_id = $2
`

type DeleteTaskParams struct {
	ID             string    `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OrganizationID)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at FROM tasks
WHERE id = $1 AND organization_id = $2
`

type GetTaskByIDParams struct {
	ID             string    `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.OrganizationID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.DueBy,
		&i.Priority,
		&i.Progress,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssignerUserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at FROM (
    SELECT id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at
    FROM tasks
    WHERE organization_id = $1
    AND (
        ($2::TEXT = 'assigned'
            AND assignee_user_id = $3
            AND ($4::UUID IS NULL OR assigner_user_id = $4::UUID)
        )
        OR
        ($2::TEXT = 'requested'
            AND assigner_user_id = $3
            AND assignee_user_id != $3
            AND ($5::UUID IS NULL OR assignee_user_id = $5::UUID)
        )
    )
    AND (
        COALESCE($6::BOOLEAN, FALSE)
        OR progress < 100
    )
    AND (
        NOT COALESCE($7::BOOLEAN, FALSE)
        OR (due_by IS NOT NULL AND due_by < CURRENT_DATE)
    )
    AND ($8::SMALLINT IS NULL OR priority >= $8::SMALLINT)
    AND ($9::TIMESTAMPTZ IS NULL OR created_at >= $9::TIMESTAMPTZ)
    ORDER BY created_at DESC
    LIMIT $10::INTEGER
) ORDER BY created_at ASC
`

type ListTasksParams struct {
	OrganizationID  uuid.UUID  `db:"organization_id" json:"organization_id"`
	Scope           string     `db:"scope" json:"scope"`
	UserID          uuid.UUID  `db:"user_id" json:"user_id"`
	AssignerID      *uuid.UUID `db:"assigner_id" json:"assigner_id"`
	AssigneeID      *uuid.UUID `db:"assignee_id" json:"assignee_id"`
	IncludeComplete *bool      `db:"include_complete" json:"include_complete"`
	PastDue         *bool      `db:"past_due" json:"past_due"`
	PriorityMin     *int16     `db:"priority_min" json:"priority_min"`
	Since           *time.Time `db:"since" json:"since"`
	Limit           int32      `db:"limit" json:"limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OrganizationID,
		arg.Scope,
		arg.UserID,
		arg.AssignerID,
		arg.AssigneeID,
		arg.IncludeComplete,
		arg.PastDue,
		arg.PriorityMin,
		arg.Since,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.DueBy,
			&i.Priority,
			&i.Progress,
			&i.Status,
			&i.AssigneeUserID,
			&i.AssignerUserID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskStatus = `-- name: SetTaskStatus :one
UPDATE tasks
SET status = $1, updated_at = now()
WHERE id = $2 and organization_id = $3
RETURNING id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at
`

type SetTaskStatusParams struct {
	Status         int16     `db:"status" json:"status"`
	ID             string    `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskStatus, arg.Status, arg.ID, arg.OrganizationID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.DueBy,
		&i.Priority,
		&i.Progress,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssignerUserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskAsAssignee = `-- name: UpdateTaskAsAssignee :one
UPDATE tasks SET
    notes = COALESCE($1, notes),
    progress = COALESCE($2, progress),
    updated_at = now()
WHERE
    id = $3
    AND organization_id = $4
    -- AND assignee_user_id = sqlc.arg('assignee_user_id')
RETURNING id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at
`

type UpdateTaskAsAssigneeParams struct {
	Notes          *string   `db:"notes" json:"notes"`
	Progress       *int16    `db:"progress" json:"progress"`
	TaskID         string    `db:"task_id" json:"task_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateTaskAsAssignee(ctx context.Context, arg UpdateTaskAsAssigneeParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAsAssignee,
		arg.Notes,
		arg.Progress,
		arg.TaskID,
		arg.OrganizationID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.DueBy,
		&i.Priority,
		&i.Progress,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssignerUserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskAsManager = `-- name: UpdateTaskAsManager :one
UPDATE tasks SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    notes = COALESCE($3, notes),
    due_by = CASE
        WHEN $4::BOOLEAN THEN NULL
        ELSE COALESCE($5, due_by)
    END,
    priority = COALESCE($6, priority),
    progress = COALESCE($7, progress),
    assignee_user_id = COALESCE($8, assignee_user_id),
    updated_at = now()
WHERE id = $9 AND organization_id = $10
RETURNING id, title, description, notes, due_by, priority, progress, status, assignee_user_id, assigner_user_id, organization_id, created_at, updated_at
`

type UpdateTaskAsManagerParams struct {
	Title          *string    `db:"title" json:"title"`
	Description    *string    `db:"description" json:"description"`
	Notes          *string    `db:"notes" json:"notes"`
	ClearDueBy     bool       `db:"clear_due_by" json:"clear_due_by"`
	DueBy          *time.Time `db:"due_by" json:"due_by"`
	Priority       *int16     `db:"priority" json:"priority"`
	Progress       *int16     `db:"progress" json:"progress"`
	AssigneeUserID *uuid.UUID `db:"assignee_user_id" json:"assignee_user_id"`
	ID             string     `db:"id" json:"id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateTaskAsManager(ctx context.Context, arg UpdateTaskAsManagerParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAsManager,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.ClearDueBy,
		arg.DueBy,
		arg.Priority,
		arg.Progress,
		arg.AssigneeUserID,
		arg.ID,
		arg.OrganizationID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.DueBy,
		&i.Priority,
		&i.Progress,
		&i.Status,
		&i.AssigneeUserID,
		&i.AssignerUserID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
