// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const disableUser = `-- name: DisableUser :one
UPDATE user_organization_assignments
SET
    disabled_at = now(),
    disabled_reason = $1::TEXT
WHERE
  user_id = $2::UUID
  AND
  organization_id = $3::UUID
RETURNING user_id, organization_id, role, disabled_at, disabled_reason, created_at
`

type DisableUserParams struct {
	DisabledReason string    `db:"disabled_reason" json:"disabled_reason"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) (UserOrganizationAssignment, error) {
	row := q.db.QueryRow(ctx, disableUser, arg.DisabledReason, arg.UserID, arg.OrganizationID)
	var i UserOrganizationAssignment
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const enableUser = `-- name: EnableUser :one
UPDATE user_organization_assignments
SET
    disabled_at = NULL,
    disabled_reason = NULL
WHERE
  user_id = $1::UUID
  AND
  organization_id = $2::UUID
RETURNING user_id, organization_id, role, disabled_at, disabled_reason, created_at
`

type EnableUserParams struct {
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) EnableUser(ctx context.Context, arg EnableUserParams) (UserOrganizationAssignment, error) {
	row := q.db.QueryRow(ctx, enableUser, arg.UserID, arg.OrganizationID)
	var i UserOrganizationAssignment
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsersWithAssignmentsByOrganizationID = `-- name: ListAllUsersWithAssignmentsByOrganizationID :many
SELECT
    u.id AS user_id,
    ua.organization_id,
    u.email,
    u.name,
    ua.role,
    ua.disabled_at,
    ua.disabled_reason
FROM users u
JOIN user_organization_assignments ua
  ON ua.user_id = u.id
WHERE ua.organization_id = $1::UUID
ORDER BY u.email
`

type ListAllUsersWithAssignmentsByOrganizationIDRow struct {
	UserID         uuid.UUID  `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID  `db:"organization_id" json:"organization_id"`
	Email          string     `db:"email" json:"email"`
	Name           string     `db:"name" json:"name"`
	Role           int16      `db:"role" json:"role"`
	DisabledAt     *time.Time `db:"disabled_at" json:"disabled_at"`
	DisabledReason *string    `db:"disabled_reason" json:"disabled_reason"`
}

func (q *Queries) ListAllUsersWithAssignmentsByOrganizationID(ctx context.Context, organizationID uuid.UUID) ([]ListAllUsersWithAssignmentsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listAllUsersWithAssignmentsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersWithAssignmentsByOrganizationIDRow
	for rows.Next() {
		var i ListAllUsersWithAssignmentsByOrganizationIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrganizationID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledUsersByOrganizationID = `-- name: ListEnabledUsersByOrganizationID :many
SELECT u.id, u.email, u.name, u.created_at
FROM users u
JOIN user_organization_assignments ua
  ON ua.user_id = u.id
WHERE ua.organization_id = $1::UUID
  AND ua.disabled_at IS NULL
AND (
    CASE WHEN $2::TEXT IS NULL THEN TRUE
    ELSE
        name ILIKE '%' || $2::TEXT || '%'
        OR
        email ILIKE '%' || $2::TEXT || '%'
    END
)
ORDER BY u.name
`

type ListEnabledUsersByOrganizationIDParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Search         *string   `db:"search" json:"search"`
}

func (q *Queries) ListEnabledUsersByOrganizationID(ctx context.Context, arg ListEnabledUsersByOrganizationIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listEnabledUsersByOrganizationID, arg.OrganizationID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET
    name = $1::TEXT
WHERE
  id = $2::UUID
RETURNING id, email, name, created_at
`

type UpdateUserNameParams struct {
	Name   string    `db:"name" json:"name"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE user_organization_assignments
SET
    role = $1::SMALLINT
WHERE
  user_id = $2::UUID
  AND
  organization_id = $3::UUID
RETURNING user_id, organization_id, role, disabled_at, disabled_reason, created_at
`

type UpdateUserRoleParams struct {
	Role           int16     `db:"role" json:"role"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UserOrganizationAssignment, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.UserID, arg.OrganizationID)
	var i UserOrganizationAssignment
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users
    (email, name)
VALUES 
    ($1, $2)
ON CONFLICT (email) DO UPDATE
    SET email = users.email -- no-op to return existing row
RETURNING id, email, name, created_at
`

type UpsertUserParams struct {
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
