#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME="onus"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Read version from VERSION file
VERSION="$(tr -d ' \n\r\t' < "$ROOT/VERSION")"
if [[ -z "$VERSION" ]]; then
    echo "VERSION file is empty" >&2
    exit 1
fi

echo -n "Building "
echo "${PROJECT_NAME} for release:"

# Prefer git info if available
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "none")"
DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

echo "    Version: $VERSION"
echo "    Commit: $COMMIT"
echo "    Date:   $DATE"
echo ""

# 1) Ensure working tree is clean (prevents “oops” releases)
if ! git -C "$ROOT" diff --quiet || ! git -C "$ROOT" diff --cached --quiet; then
    echo "WARNING: tree has uncommitted changes. Commit/stash before releasing." >&2
fi

# 2) Create / update webapp version module
cat > "$ROOT/webapp/src/lib/version.ts" <<EOF
// Generated by scripts/release.sh — do not edit.
export const VERSION = "${VERSION}";
export const COMMIT = "${COMMIT}";
export const BUILD_DATE = "${DATE}";
EOF

# 3) Build and push Docker image
IMAGE="ghcr.io/goodieshq/onus"

arch="$(uname -m)"
case "$arch" in
    x86_64)
        platform="linux/amd64" ;;
    arm64|aarch64)
        platform="linux/arm64" ;;
    *)
        echo "Unsupported host arch: $arch" >&2
        exit 1
        ;;
esac
docker buildx build \
    --platform "${platform}" \
    -t "${IMAGE}:${VERSION}" \
    --build-arg "ONUS_VERSION=${VERSION}" \
    --build-arg "ONUS_COMMIT=${COMMIT}" \
    --build-arg "ONUS_BUILD_DATE=${DATE}" \
    --load \
    "$ROOT"

echo "Docker image built:"
echo "    ${IMAGE}:${VERSION}"

echo "Build complete: ${VERSION}"