#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME="onus"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Read version from VERSION file
VERSION="$(tr -d ' \n\r\t' < "$ROOT/VERSION")"
if [[ -z "$VERSION" ]]; then
    echo "VERSION file is empty" >&2
    exit 1
fi
TAG="v${VERSION}"

echo -n "Building "
echo "${PROJECT_NAME} for release:"

# Prefer git info if available
COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "none")"
DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

echo "    Version: $VERSION"
echo "    Commit: $COMMIT"
echo "    Date:   $DATE"
echo ""

# 1) Ensure working tree is clean (prevents “oops” releases)
if ! git -C "$ROOT" diff --quiet || ! git -C "$ROOT" diff --cached --quiet; then
    echo "Working tree has uncommitted changes. Commit/stash before releasing." >&2
    exit 1
fi

# 2) Create / update webapp version module
cat > "$ROOT/webapp/src/lib/version.ts" <<EOF
// Generated by scripts/release.sh — do not edit.
export const VERSION = "${VERSION}";
export const COMMIT = "${COMMIT}";
export const BUILD_DATE = "${DATE}";
EOF

# 3) Build and push Docker image
IMAGE="ghcr.io/goodieshq/onus"

docker buildx build \
    --platform "linux/amd64,linux/arm64" \
    -t "${IMAGE}:${VERSION}" \
    -t "${IMAGE}:latest" \
    --build-arg "ONUS_VERSION=${VERSION}" \
    --build-arg "ONUS_COMMIT=${COMMIT}" \
    --build-arg "ONUS_BUILD_DATE=${DATE}" \
    --push \
    "$ROOT"
echo "Docker image pushed:"
echo "    ${IMAGE}:${VERSION}"
echo "    ${IMAGE}:latest"

# 5) Git tag (annotated)
if git -C "$ROOT" rev-parse "$TAG" >/dev/null 2>&1; then
    echo "Git tag ${TAG} already exists" >&2
    exit 1
fi

git -C "$ROOT" tag -a "$TAG" -m "Release $TAG"
git -C "$ROOT" push origin "$TAG"

echo "Release complete: ${TAG}"